// One-off: Vietnamese diacritics + backend message localization. Run: node scripts/vi-polish.cjs
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

const FRONT = [
  ['hoac ten', 'hoặc tên'],
  ['hoac ', 'hoặc '],
  ['tac gia', 'tác giả'],
  ['phai ', 'phải '],
  ['khong ', 'không '],
  ['nhung ', 'nhưng '],
  ['theo doi', 'theo dõi'],
  ['Moi ', 'Mới '],
  ['duyet', 'duyệt'],
  ['choi', 'chơi'],
  ['Dang ', 'Đăng '],
  ['da ', 'đã '],
  ['hoi dap', 'hỏi đáp'],
  ['bai ', 'bài '],
  ['bai<', 'bài<'],
  ['cho duyet', 'chờ duyệt'],
  ['da duyet', 'đã duyệt'],
  ['tu choi', 'từ chối'],
  ['chu de', 'chủ đề'],
  ['that', 'thật'],
  ['thay chu ', 'thấy chữ '],
  ['kiem soat', 'kiểm soát'],
  [' o ', ' ở '],
  ['kem ', 'kèm '],
  [' co ', ' có '],
  ['gui ', 'gửi '],
  ['bai viet', 'bài viết'],
  ['nguoi dung', 'người dùng'],
  [' tu ', ' từ '],
  [' mo', ' mở'],
  ['dang text', 'dạng text'],
  ['Khong gian', 'Không gian'],
  ['tu cach', 'tư cách'],
  ['tai lai trang', 'tải lại trang'],
  ['cau hoi', 'câu hỏi'],
  ['dau tien', 'đầu tiên'],
  ['hoc sinh', 'học sinh'],
  ['ket qua', 'kết quả'],
  ['van de', 'vấn đề'],
  ['o day', 'ở đây'],
  ['dang ', 'đăng '],
  ['tren ', 'trên '],
  ['nhap', 'nhập'],
  ['tiet', 'tiết'],
  ['Khoa', 'Khóa'],
  ['Moi duoc duyet', 'Mới được duyệt'],
  ['Ha quyen user', 'Hạ quyền user'],
  ['Len admin', 'Lên admin'],
  ['Vi du', 'Ví dụ'],
  ['goc nhin', 'góc nhìn'],
  ['ten ai', 'tên ai'],
  ['ai do', 'ai đó'],
  ['tra loi', 'trả lời'],
  ['Huy', 'Hủy'],
  ['Viet ', 'Viết '],
  ['nay', 'này'],
  ['cung ', 'cùng '],
  [' ma ', ' mà '],
  [' thi ', ' thì '],
  [' moi ', ' mới '],
  ['Dang nhap de tha cam xuc', 'Đăng nhập để thả cảm xúc'],
  ['Dang nhap de bieu cam', 'Đăng nhập để biểu cảm'],
  ['Dang nhap de binh luan va tra loi', 'Đăng nhập để bình luận và trả lời'],
  ['Dang nhap de binh luan', 'Đăng nhập để bình luận'],
  ['Dang nhap de tra loi', 'Đăng nhập để trả lời'],
  ['Dang nhap de dang bai dau tien', 'Đăng nhập để đăng bài đầu tiên'],
  ['Dang nhap de theo doi bai', 'Đăng nhập để theo dõi bài'],
  ['Dang nhap', 'Đăng nhập'],
  ['Dang ky', 'Đăng ký'],
  ['Dang xuat', 'Đăng xuất'],
  ['Dang tai', 'Đang tải'],
  ['Dang gui', 'Đang gửi'],
  ['Dang tra loi', 'Đang trả lời'],
  ['Dang cho admin xem', 'Đang chờ admin xem'],
  ['Cho duyet', 'Chờ duyệt'],
  ['Da duyet', 'Đã duyệt'],
  ['Da gui bai', 'Đã gửi bài'],
  ['Da gui', 'Đã gửi'],
  ['Da chon', 'Đã chọn'],
  ['Da co tai khoan', 'Đã có tài khoản'],
  ['Bi tu choi', 'Bị từ chối'],
  ['Chua co confession nao', 'Chưa có confession nào'],
  ['Chua co', 'Chưa có'],
  ['chua gui', 'chưa gửi'],
  ['Bai viet moi', 'Bài viết mới'],
  ['Bai viet', 'Bài viết'],
  ['Bai cua toi', 'Bài của tôi'],
  ['Bai cua ban se hien', 'Bài của bạn sẽ hiện'],
  ['Bai ban gui', 'Bài bạn gửi'],
  ['Bai duyet se hien', 'Bài duyệt sẽ hiện'],
  ['Bai gui se hien', 'Bài gửi sẽ hiện'],
  ['Bai o trang thai cho duyet', 'Bài ở trạng thái chờ duyệt'],
  ['Bai duoc duyet', 'Bài được duyệt'],
  ['Bai se hien', 'Bài sẽ hiện'],
  ['Bai moi', 'Bài mới'],
  ['Cau hoi moi', 'Câu hỏi mới'],
  ['Cau hoi dau tien', 'Câu hỏi đầu tiên'],
  ['Cau hoi', 'Câu hỏi'],
  ['Cau tra loi dau tien', 'Câu trả lời đầu tiên'],
  ['Cau tra loi nay', 'Câu trả lời này'],
  ['Cau tra loi cua ban', 'Câu trả lời của bạn'],
  ['Cau tra loi', 'Câu trả lời'],
  ['Chon cau tra loi nay', 'Chọn câu trả lời này'],
  ['Tra loi', 'Trả lời'],
  ['Binh luan voi tu cach admin', 'Bình luận với tư cách admin'],
  ['Binh luan hien ten that', 'Bình luận hiện tên thật'],
  ['Binh luan cua ban', 'Bình luận của bạn'],
  ['Binh luan', 'Bình luận'],
  ['binh luan', 'bình luận'],
  ['Gui confession', 'Gửi confession'],
  ['Gui binh luan', 'Gửi bình luận'],
  ['Gui tra loi', 'Gửi trả lời'],
  ['Gui bai', 'Gửi bài'],
  ['Xoa bai', 'Xóa bài'],
  ['Xoa confession', 'Xóa confession'],
  ['Duyet bai', 'Duyệt bài'],
  ['Tu choi', 'Từ chối'],
  ['Ly do', 'Lý do'],
  ['Nguoi dung', 'Người dùng'],
  ['Bao cao', 'Báo cáo'],
  ['bao cao', 'báo cáo'],
  ['Quan tri', 'Quản trị'],
  ['Tong quan', 'Tổng quan'],
  ['Hoi dap', 'Hỏi đáp'],
  ['Chuyen muc', 'Chuyên mục'],
  ['chuyen muc', 'chuyên mục'],
  ['Tieu de', 'Tiêu đề'],
  ['tieu de', 'tiêu đề'],
  ['Noi dung that', 'Nội dung thật'],
  ['Noi dung khong phu hop', 'Nội dung không phù hợp'],
  ['Noi dung', 'Nội dung'],
  ['noi dung', 'nội dung'],
  ['Mat khau', 'Mật khẩu'],
  ['Ten hien thi', 'Tên hiển thị'],
  ['ten admin', 'tên admin'],
  ['Thu hoi binh luan nay', 'Thu hồi bình luận này'],
  ['Thu hoi', 'Thu hồi'],
  ['Thich', 'Thích'],
  ['Phan no', 'Phẫn nộ'],
  ['Cam xuc', 'Cảm xúc'],
  ['cam xuc', 'cảm xúc'],
  ['Xin chao', 'Xin chào'],
  ['Quay lai', 'Quay lại'],
  ['Mo khoa', 'Mở khóa'],
  ['Tim theo', 'Tìm theo'],
  ['Tim nguoi dung', 'Tìm người dùng'],
  ['Tim bai viet', 'Tìm bài viết'],
  ['Khong con bai', 'Không còn bài'],
  ['Khong co', 'Không có'],
  ['Khong dang', 'Không đăng'],
  ['Khong phu hop', 'Không phù hợp'],
  ['Khong tai duoc', 'Không tải được'],
  ['khong luu', 'không lưu'],
  ['Khong an danh', 'Không ẩn danh'],
  ['khong an danh', 'không ẩn danh'],
  ['An danh', 'Ẩn danh'],
  ['an danh', 'ẩn danh'],
  ['Chia se that', 'Chia sẻ thật'],
  ['Chia se an danh', 'Chia sẻ ẩn danh'],
  ['Chia se dieu', 'Chia sẻ điều'],
  ['chia se', 'chia sẻ'],
  ['Dien dan', 'Diễn đàn'],
  ['hoc tap', 'học tập'],
  ['Lap trinh', 'Lập trình'],
  ['Vat ly', 'Vật lý'],
  ['Toan hoc', 'Toán học'],
  ['Toan va', 'Toán và'],
  ['Dat cau hoi', 'Đặt câu hỏi'],
  ['dat cau hoi', 'đặt câu hỏi'],
  ['luot xem', 'lượt xem'],
  ['vua xong', 'vừa xong'],
  ['phut truoc', 'phút trước'],
  ['gio truoc', 'giờ trước'],
  ['ngay truoc', 'ngày trước'],
  ['truoc khi hien', 'trước khi hiện'],
  ['hien o day', 'hiện ở đây'],
  ['hien cong khai', 'hiện công khai'],
  ['hien thi', 'hiển thị'],
  ['se hien', 'sẽ hiện'],
  ['se thay', 'sẽ thấy'],
  ['Ban se', 'Bạn sẽ'],
  ['ban se', 'bạn sẽ'],
  ['Ban co the', 'Bạn có thể'],
  ['ban co the', 'bạn có thể'],
  ['Ban theo doi', 'Bạn theo dõi'],
  ['bai dau tien', 'bài đầu tiên'],
  ['nguoi dau tien', 'người đầu tiên'],
  ['cua ban', 'của bạn'],
  ['cua minh', 'của mình'],
  ['cua toi', 'của tôi'],
  ['Ban gui', 'Bạn gửi'],
  ['ban gui', 'bạn gửi'],
  ['muon noi', 'muốn nói'],
  ['giup ban', 'giúp bạn'],
  ['de theo doi', 'để theo dõi'],
  ['de binh luan', 'để bình luận'],
  ['de tra loi', 'để trả lời'],
  ['de dang bai', 'để đăng bài'],
  ['de bieu cam', 'để biểu cảm'],
  ['de tha cam xuc', 'để thả cảm xúc'],
  ['de nhan', 'để nhận'],
  ['de cong dong', 'để cộng đồng'],
  ['Hang doi dang sach', 'Hàng đợi đang trống'],
  ['ben duoi', 'bên dưới'],
  ['cung bi xoa', 'cũng bị xóa'],
  ['bi xoa', 'bị xóa'],
  ['moi tac dong', 'mọi tác động'],
  ['Moi tac dong', 'Mọi tác động'],
  ['Kiem soat', 'Kiểm soát'],
  ['tiep tuc', 'tiếp tục'],
  ['vi pham', 'vi phạm'],
  ['vinh vien', 'vĩnh viễn'],
  ['thong tin ca nhan', 'thông tin cá nhân'],
  ['dung trong tam', 'đúng trọng tâm'],
  ['lich su', 'lịch sự'],
  ['van minh', 'văn minh'],
  ['Viet lich su', 'Viết lịch sự'],
  ['Viet dieu', 'Viết điều'],
  ['viet moi', 'viết mới'],
  ['Toi da 200', 'Tối đa 200'],
  ['Toi thieu', 'Tối thiểu'],
  ['toi da 5000', 'tối đa 5000'],
  ['ky tu', 'ký tự'],
  ['Vui long', 'Vui lòng'],
  ['vui long', 'vui lòng'],
  ['nhap noi dung', 'nhập nội dung'],
  ['Hay la', 'Hãy là'],
  ['Hay tao', 'Hãy tạo'],
  ['Hay dat', 'Hãy đặt'],
  ['Tao tai khoan', 'Tạo tài khoản'],
  ['tat ca', 'tất cả'],
  ['Tat ca', 'Tất cả'],
  ['Loc theo', 'Lọc theo'],
  ['Loai noi dung', 'Loại nội dung'],
  ['Chi tiet', 'Chi tiết'],
  ['kem vi du', 'kèm ví dụ'],
  ['neu co', 'nếu có'],
  ['cu the', 'cụ thể'],
  ['Go @ten', 'Gõ @tên'],
  ['Go @ de', 'Gõ @ để'],
  ['tag ai do', 'tag ai đó'],
  ['Dieu huong chinh', 'Điều hướng chính'],
  ['Mo menu', 'Mở menu'],
  ['Doi giao dien', 'Đổi giao diện'],
  ['Lien ket phu', 'Liên kết phụ'],
  ['Cong dong', 'Cộng đồng'],
  ['cong dong', 'cộng đồng'],
  ['kiem duyet', 'kiểm duyệt'],
  ['phe duyet', 'phê duyệt'],
  ['chap nhan', 'chấp nhận'],
  ['cong khai', 'công khai'],
  ['thong bao', 'thông báo'],
  ['trang thai', 'trạng thái'],
  ['Trang thai', 'Trạng thái'],
  ['tai khoan', 'tài khoản'],
  ['hien tai', 'hiện tại'],
  ['o muc', 'ở mục'],
  ['kem trang thai', 'kèm trạng thái'],
  ['Doc them', 'Đọc thêm'],
  ['Thao luan', 'Thảo luận'],
  ['Mo ta', 'Mô tả'],
  ['Dung Gmail', 'Dùng Gmail'],
  ['that de nhan', 'thật để nhận'],
  ['Giai phuong trinh nay the nao', 'Giải phương trình này thế nào'],
  ['da thu cach nao', 'đã thử cách nào'],
  ['Ban da thu', 'Bạn đã thử'],
  ['Cach on thi', 'Cách ôn thi'],
  ['hieu qua', 'hiệu quả'],
  ['Cach confession hoat dong', 'Cách confession hoạt động'],
  ['Nhom hoc sinh', 'Nhóm học sinh'],
  ['trao doi', 'trao đổi'],
  ['trong thu vien', 'trong thư viện'],
  ['Goc hoc tap', 'Góc học tập'],
  ['yen tinh', 'yên tĩnh'],
  ['Vao forum', 'Vào forum'],
  ['Danh dau da xu ly', 'Đánh dấu đã xử lý'],
  ['Danh dau', 'Đánh dấu'],
  ['Bo qua', 'Bỏ qua'],
  ['quan ly', 'quản lý'],
  ['Xu ly', 'Xử lý'],
  ['xu ly', 'xử lý'],
  ['Submit failed', 'Gửi thất bại, thử lại sau'],
  ['Load failed', 'Không tải được dữ liệu'],
  ['Approve failed', 'Duyệt thất bại'],
  ['Reject failed', 'Từ chối thất bại'],
  ['Login failed', 'Đăng nhập thất bại'],
  ['Register failed', 'Đăng ký thất bại'],
  ['Khong hien', 'Không hiện'],
  ['o trang thai', 'ở trạng thái'],
  ['Gui', 'Gửi'],
  ['Xoa', 'Xóa'],
  ['Duyet', 'Duyệt'],
  ['Khong', 'Không'],
  ['cua', 'của'],
  ['hien', 'hiện'],
  ['duoc', 'được'],
  ['nao', 'nào'],
  [' de ', ' để '],
  [' va ', ' và '],
  [' la ', ' là '],
  [' voi ', ' với '],
  [' cac ', ' các '],
];

const BACK = [
  ["'Invalid email'", "'Email không hợp lệ'"],
  ["'Invalid displayName (1-50 chars)'", "'Tên hiển thị 1-50 ký tự'"],
  ["'Password must be 8-128 chars'", "'Mật khẩu 8-128 ký tự'"],
  ["'Email already registered'", "'Email đã được đăng ký'"],
  ["'Invalid JSON'", "'Dữ liệu không hợp lệ'"],
  ["'Invalid credentials'", "'Email hoặc mật khẩu chưa đúng'"],
  ["'Account is ' + user.status", "'Tài khoản không còn hoạt động'"],
  ["'Unauthorized'", "'Bạn chưa đăng nhập'"],
  ["'Forbidden'", "'Bạn không có quyền'"],
  ["'Not found or not pending'", "'Bài không tồn tại hoặc đã được xử lý'"],
  ["'Not found'", "'Không tìm thấy'"],
  ["'Invalid status'", "'Trạng thái không hợp lệ'"],
  ["'role must be user|admin'", "'Vai trò phải là user hoặc admin'"],
  ["'Admin route not found'", "'Không tìm thấy chức năng admin'"],
  ["'title/content required'", "'Tiêu đề và nội dung là bắt buộc'"],
  ["'content required (1-5000 chars)'", "'Nội dung từ 1 đến 5000 ký tự'"],
  ["'content required'", "'Nội dung là bắt buộc'"],
  ["'target_type (post|question|answer|confession), target_id, content required'", "'Thiếu loại, id hoặc nội dung'"],
  ["'target_type (post|question|answer), target_id, content required'", "'Thiếu loại, id hoặc nội dung'"],
  ["'target_type, target_id, reason required'", "'Thiếu đối tượng hoặc lý do'"],
  ["'parent_id must be numeric'", "'parent_id phải là số'"],
  ["'Parent comment not found on this target'", "'Không tìm thấy bình luận gốc'"],
  ["'target_type + numeric target_id required'", "'Thiếu loại hoặc id'"],
  ["'target_type, numeric target_id, kind (like|haha|angry) required'", "'Thiếu loại, id hoặc cảm xúc'"],
  ["'Method not allowed'", "'Phương thức không được hỗ trợ'"],
  ["'Too many requests'", "'Bạn thao tác quá nhanh, thử lại sau'"],
  ["?? 'Rejected'", "?? 'Không phù hợp'"],
];

function walk(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name === 'node_modules' || e.name === '.wrangler' || e.name === 'dist') continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else if (/\.(jsx|js|ts)$/.test(e.name) && !e.name.endsWith('.polish.cjs')) out.push(p);
  }
  return out;
}

function apply(file, pairs) {
  let s = fs.readFileSync(file, 'utf8');
  let n = 0;
  // Longest first so specifics (da duyet) win over generics (da ).
  const ordered = pairs.slice().sort((a, b) => b[0].length - a[0].length);
  for (const [a, b] of ordered) {
    if (s.includes(a)) {
      s = s.split(a).join(b);
      n++;
    }
  }
  if (n > 0) fs.writeFileSync(file, s, 'utf8');
  return n;
}

const changed = [];
for (const f of walk(ROOT)) {
  const rel = path.relative(ROOT, f);
  const pairs = rel.startsWith('worker' + path.sep) ? BACK : FRONT;
  const n = apply(f, pairs);
  if (n > 0) changed.push(`${rel}: ${n}`);
}
console.log(changed.join('\n') || 'no changes');
